<?php

/*********************************************************************
* Extension configuration file for ext "rss_display".
*
* Generated by ext 03-05-2014 13:53 UTC
*
* https://github.com/t3elmar/Ext
*********************************************************************/

$EM_CONF[$_EXTKEY] = array (
  'title' => 'RSS Feed Display',
  'description' => 'Fetch a RSS / Atom Feed and display its content on the Frontend.',
  'category' => 'plugin',
  'version' => '3.0.0',
  'state' => 'stable',
  'author' => 'Fabien Udriot',
  'author_email' => 'fabien.udriot@ecodev.ch',
  'author_company' => 'Ecodev',
  'constraints' =>
  array (
    'depends' =>
    array (
      'typo3' => '7.5.0-7.99.99',
      'fluid' => '',
      'extbase' => '',
    ),
    'conflicts' =>
    array (
    ),
    'suggests' =>
    array (
    ),
  ),
  'suggests' =>
  array (
  ),
);
