<?php

/*********************************************************************
* Extension configuration file for ext "rss_display".
*
* Generated by ext 22-01-2014 06:42 UTC
*
* https://github.com/t3elmar/Ext
*********************************************************************/

$EM_CONF[$_EXTKEY] = array (
  'title' => 'RSS Feed Display',
  'description' => 'Fetch the content of a RSS Feed and display it on the Frontend.',
  'category' => 'plugin',
  'shy' => 0,
  'version' => '2.1.0-dev',
  'dependencies' => '',
  'conflicts' => '',
  'priority' => '',
  'loadOrder' => '',
  'module' => '',
  'state' => 'stable',
  'uploadfolder' => 0,
  'createDirs' => '',
  'modify_tables' => '',
  'clearcacheonload' => 0,
  'lockType' => '',
  'author' => 'Fabien Udriot',
  'author_email' => 'fabien.udriot@ecodev.ch',
  'author_company' => 'Ecodev',
  'CGLcompliance' => '',
  'CGLcompliance_note' => '',
  'constraints' => 
  array (
    'depends' => 
    array (
      'typo3' => '4.5.0-4.5.99',
      'fluid' => '',
      'extbase' => '',
    ),
    'conflicts' => 
    array (
    ),
    'suggests' => 
    array (
    ),
  ),
  'suggests' => 
  array (
  ),
  'user' => 'fab1en',
  'comment' => 'Change log http://forge.typo3.org/projects/extension-rss_display/versions/2642. Major rewrite, please run the update script in the EM.',
);

?>